// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE0tMMs0FKSU7exySlTRtkdikiiF42Htg',
    appId: '1:614588481077:web:0451fe213bf9f81a5fbb7c',
    messagingSenderId: '614588481077',
    projectId: 'burgan-task',
    authDomain: 'burgan-task.firebaseapp.com',
    storageBucket: 'burgan-task.appspot.com',
    measurementId: 'G-TW7VWFZRKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdvHzoZG1ytJGuFtCZGbQVCXMFxl93A1o',
    appId: '1:614588481077:android:19b23cc941a317ce5fbb7c',
    messagingSenderId: '614588481077',
    projectId: 'burgan-task',
    storageBucket: 'burgan-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu5x01rjDABrWPEw7od9dOLDUSIx2Jo7g',
    appId: '1:614588481077:ios:aa97366ce8138ee75fbb7c',
    messagingSenderId: '614588481077',
    projectId: 'burgan-task',
    storageBucket: 'burgan-task.appspot.com',
    iosBundleId: 'com.example.burganTask.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu5x01rjDABrWPEw7od9dOLDUSIx2Jo7g',
    appId: '1:614588481077:ios:aa97366ce8138ee75fbb7c',
    messagingSenderId: '614588481077',
    projectId: 'burgan-task',
    storageBucket: 'burgan-task.appspot.com',
    iosBundleId: 'com.example.burganTask.RunnerTests',
  );
}
